### ISSUE TITLE
Segvault when stopping backend (supervisor)

### ISSUE THREAD

**Issue by tijno** [bitclout/backend#73]
I am running backend using supervisor. 

When i issue a `supervisorctl stop bitclout` it results in a Segfault.

https://github.com/bitclout/backend/blob/2ed0152433d52ea38e9a010983c7fdbe47a706f7/routes/server.go#L1151

```
I0707 14:44:25.979160   25058 server.go:1140] APIServer.Stop: Gracefully shutting down APIServer
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x238 pc=0xf2f7f0]

goroutine 1 [running]:
github.com/bitclout/backend/routes.(*APIServer).Stop(...)
        /src/backend/routes/server.go:1141
github.com/bitclout/backend/cmd.(*Node).Stop(0xc108e16d48)
        /src/backend/cmd/node.go:99 +0x90
github.com/bitclout/backend/cmd.Run.func1(0xc108e16d48)
        /src/backend/cmd/run.go:37 +0x2f
github.com/bitclout/backend/cmd.Run(0x1d438e0, 0xc000896100, 0x0, 0x2)
        /src/backend/cmd/run.go:42 +0x1a6
github.com/spf13/cobra.(*Command).execute(0x1d438e0, 0xc0008960e0, 0x2, 0x2, 0x1d438e0, 0xc0008960e0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1d43660, 0xf331f0, 0x0, 0x0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/bitclout/backend/cmd.Execute()
        /src/backend/cmd/root.go:24 +0x2d
main.main()
        /src/backend/main.go:15 +0x25
```

I am trying to find a way to gracefully shutdown backend, as ctrl C or this segv seem often to trigger corruption in TxIndex with "Duppl Block" errors and having to restart TxIndex.

**Comment by maebeam** [comment]
Thanks for reporting! I'll prioritize this

**Comment by tijno** [comment]
Looks like this is still an issue - I was hoping https://github.com/bitclout/core/pull/75 https://github.com/bitclout/core/pull/74 would fix this, but backend still crashing on shutdown.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0xf63770]

goroutine 1 [running]:
github.com/bitclout/backend/routes.(*APIServer).Stop(...)
        /src/backend/routes/server.go:1194
github.com/bitclout/backend/cmd.(*Node).Stop(0xc000063d48)
        /src/backend/cmd/node.go:74 +0x90
github.com/bitclout/backend/cmd.Run.func1(0xc000063d48)
        /src/backend/cmd/run.go:38 +0x2f
github.com/bitclout/backend/cmd.Run(0x1da4520, 0xc0003f7dc0, 0x0, 0x2)
        /src/backend/cmd/run.go:43 +0x1a6
github.com/spf13/cobra.(*Command).execute(0x1da4520, 0xc0003f7da0, 0x2, 0x2, 0x1da4520, 0xc0003f7da0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1da42a0, 0xf67450, 0x0, 0x0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/bitclout/backend/cmd.Execute()
        /src/backend/cmd/root.go:24 +0x2d
main.main()
        /src/backend/main.go:15 +0x25
```

**Comment by gfodor** [comment]
Yes my PR should resolve this, there are two bugs.

**Comment by maebeam** [comment]
Closing this, thanks @gfodor
